### ISSUE TITLE
hola lo mio es mas un problema con la traduccion de los dialogos

### ISSUE THREAD

**Issue by daruiiii** [Mexes-GM/DawnCraft-Traduccion-ES#1]
con solo entrar al juego y hablarle al primer npc el arbolito ese no me traduce nada del texto no se si es un problema mio

**Comment by Mexes-GM** [comment]
Actualmente no estoy solucionando ningún problema, estoy esperando a que salga de beta para traducirlo nuevamente.

Sin embargo ese problema que me dice estaba solucionado debes de tener algo mal instalado
