### ISSUE TITLE
Error al iniciar partida

### ISSUE THREAD

**Issue by Jvbreadd** [Mexes-GM/DawnCraft-Traduccion-ES#2]
intento entrar en un mundo nuevo y me dice que los paquetes de datos estan mal, me da la opcion de volver al menu o iniciar en modo seguro, si le doy a modo seguro se queda cargando pero no arranca y si le doy a volver al menu pues eso, vuelve, segui los pasos al pie de la letra y de hecho no es la primera vez que lo traduzco asi

**Comment by Mexes-GM** [comment]
Que version de dawncraft esta utilizando?

**Comment by Jvbreadd** [comment]
la ultima de curseforge

**Comment by Jvbreadd** [comment]
no me habia fijado que se puede cambiar la version en curseforge, y si era eso el problema xd, muchísimas gracias ya llevaba hora y pico intentando arreglarlo

**Comment by Mexes-GM** [comment]
Pronto actualizare la traducción a una versión mas reciente del mod.
