### ISSUE TITLE
No funciona el pack al aplicar la traducción

### ISSUE THREAD

**Issue by YaelArquero** [Mexes-GM/DawnCraft-Traduccion-ES#4]
He probado a jugar el modpack directamente y funciona, pero al meter las carpetas dentro de la carpeta raíz del modpack no me deja crear un mundo, aparece la siguiente pantalla
![Captura de pantalla 2024-07-03 035842](https://github.com/Mexes-GM/DawnCraft-Traduccion-ES/assets/174565000/da2e6425-8436-47ec-956d-55cd5bc216be)

**Comment by JohanGr13** [comment]
Tengo el mismo problema, no funciona. 
Alguna solucion ?
![image](https://github.com/Mexes-GM/DawnCraft-Traduccion-ES/assets/174578922/a54c12c5-bcda-48a1-ad5e-7745cb30226b)

**Comment by Mexes-GM** [comment]
La ultima actualización de la traducción fue para la versión **2.0.1 (BETA)** del modpack, si esta utilizando una versión del modpack superior a la de la traducción seguramente esta falle y seguramente sea el motivo por el que les falla. Pronto actualizare la traducción a una versión mas reciente.

**Comment by YaelichuXD** [comment]
Y sabe si hay alguna manera de descargar la versión 1.33 del modpack desde curseforge?
Muchas gracias

**Comment by YaelArquero** [comment]
Vale, perfecto gracias
